### PR TITLE
Detect flow source / target changes

### LINKED ISSUE #18: Edge is wrongly classified as layoutChange
### Describe the Bug
I have a simple BPMN diagram where a new service was added. The edge going from A to End is now an edge from A to B. It is wrongly classified as a layoutchange only whereas it is a semantical change:

image

The JSON diff is this:
```
{
	"_layoutChanged": {
		"Flow_0dhn14f": {
			"$type": "bpmn:SequenceFlow",
			"id": "Flow_0dhn14f"
		}
	},
	"_changed": {},
	"_removed": {},
	"_added": {
		"Activity_0d0duli": {
			"$type": "bpmn:Task",
			"id": "Activity_0d0duli",
			"name": "B"
		},
		"Flow_19qppgm": {
			"$type": "bpmn:SequenceFlow",
			"id": "Flow_19qppgm"
		}
	}
}
```

### Steps to Reproduce

1. Create simple flow with Start -> A -> End.
2. Save this as version 1
3. Drag a new service on the edge between A and End.
4. Save this as version 2
5. Import version 1 and version 2 into https://demo.bpmn.io/diff

### Expected Behavior

Exepected would have been for it to go into the "changed" section.

### Environment

I used the only version of https://demo.bpmn.io/diff as well as running locally with "bpmn-js-differ": "2.0.2".

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

The PR does not use plain object diffing for [moddle](https://github.com/bpmn-io/moddle) elements, but rather uses the moddle meta-data to figure what is supposed to be diffed.

This ensures we're able to diff otherwise hidden references, too, such as `Flow#target`.

Closes https://github.com/bpmn-io/bpmn-js-differ/issues/18.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
CC @nithinssabu

**Comment by nikku** [comment]
@nithinssabu via https://github.com/bpmn-io/bpmn-js-differ/pull/22/commits/7ffa85264743b9560683f815476ff97fd5a42b31 I sketched how a special differ, aware of `moddle` elements can be added to the diff utility. As discussed we may then want to use the [`moddle` introspection utilities](https://github.com/bpmn-io/moddle?tab=readme-ov-file#introspect-things) to iterate through _all_ available properties.

**Comment by nikku** [comment]
Via https://github.com/bpmn-io/bpmn-js-differ/pull/22/commits/142c8b1dea79d5e9491cf15dc1f52e62443f81cf I sketch how the actual diffing would work; still two rough edges to sort out.

**Comment by nikku** [comment]
I moved this to `review` as it [works good on my machine](https://github.com/nikku/works-on-my-machine). Feedback welcome.

**Comment by nikku** [comment]
As discussed @philippfromme, please have a look.

**Review by philippfromme — APPROVED** [review]
Great job! 🚀 Thanks again for walking us through the pull request. It helped tremendously. I added [one more assertion](https://github.com/bpmn-io/bpmn-js-differ/pull/22/commits/5fbf42847404648ee84c197a53380f03f602b817) to validate the `#ref:<NAME>` scheme.

**Comment by nikku** [comment]
This is relased as [v3.0.0](https://github.com/bpmn-io/bpmn-js-differ/releases/tag/v3.0.0).

**Comment by nithinssabu** [comment]
This could have introduced a bug in the library. See https://github.com/camunda/web-modeler/pull/10621#issuecomment-2311946929

**Comment by nithinssabu** [comment]
> This could have introduced a bug in the library. See [camunda/web-modeler#10621 (comment)](https://github.com/camunda/web-modeler/pull/10621#issuecomment-2311946929)

Created a [minimal reproducer](https://codesandbox.io/p/sandbox/bpmn-js-differ-bug-jq5srp). Just change the `bpmn-js-differ` versions between `2.0.2` and `3.0.0` to see the difference in changes count.

**Comment by nikku** [comment]
Thanks for the report and steps to reproduce @nithinssabu. 

As always, let's create a new bug report and take it from there :arrow_right: https://github.com/bpmn-io/bpmn-js-differ/issues/24.

**Pull request merged**
